"""First Migrate Commit

Revision ID: 7ec4f5d878ae
Revises: 
Create Date: 2019-09-02 00:10:03.106798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec4f5d878ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermodel_email'), 'usermodel', ['email'], unique=False)
    op.create_index(op.f('ix_usermodel_username'), 'usermodel', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodel_username'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_email'), table_name='usermodel')
    op.drop_table('usermodel')
    # ### end Alembic commands ###
